1

In [1]:
import numpy as np

In [1]:
import matplotlib.pyplot as plt


ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2

In [3]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4

In [ ]:
array_3x3x3 = np.random.random((3, 3, 3))
print("3x3x3 Random Array:\n", array_3x3x3)


3x3x3 Random Array:
 [[[0.72021247 0.52523851 0.82432666]
  [0.90857585 0.65188066 0.25742985]
  [0.21941095 0.72919431 0.74501183]]

 [[0.43437488 0.45063235 0.77063789]
  [0.82198114 0.52142916 0.65481426]
  [0.52704471 0.15731767 0.62488608]]

 [[0.29374828 0.93231385 0.75568671]
  [0.44960116 0.42748357 0.39124127]
  [0.31210534 0.54180215 0.76635807]]]


5

In [ ]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Min Value: ", min_value)
print("Max Value: ", max_value)

Min Value:  0.03505796908275294
Max Value:  0.9989706937511695


6

In [ ]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print("Mean Value: ", mean_value)

Mean Value:  0.46503241301369563


7

In [ ]:
random_5x5 = np.random.random((5, 5))
normalized_5x5 = (random_5x5 - random_5x5.min()) / (random_5x5.max() - random_5x5.min())
print("Normalized 5x5 Array:", normalized_5x5)

Normalized 5x5 Array: [[0.27450177 0.64497116 0.         0.60904658 0.91505862]
 [0.97466171 0.90157579 0.89002137 0.93516864 1.        ]
 [0.30633413 0.68025654 0.03210355 0.56913902 0.52308955]
 [0.40851734 0.27837396 0.74800442 0.32552448 0.85965385]
 [0.08055783 0.32598061 0.4938373  0.15105875 0.79461554]]


8

In [ ]:
matrix_A = np.random.random((5, 3))
matrix_B = np.random.random((3, 2))
matrix_product = np.dot(matrix_A, matrix_B)
print("Matrix A:\n", matrix_A)
print("Matrix B:\n", matrix_B)

Matrix A:
 [[0.18642228 0.58242555 0.67667069]
 [0.26567353 0.96570378 0.68516045]
 [0.66948985 0.03326531 0.7428195 ]
 [0.28955596 0.40558985 0.30098538]
 [0.16491245 0.90651076 0.55784665]]
Matrix B:
 [[0.8420689  0.2815159 ]
 [0.29779077 0.75151119]
 [0.90170017 0.81190333]]


9

In [ ]:
matrix_C = np.random.random((3, 3))
matrix_D = np.random.random((3, 3))
dot_product = np.dot(matrix_C, matrix_D)
print("Matrix C:\n", matrix_C)
print("Matrix D:\n", matrix_D)

Matrix C:
 [[0.19440588 0.17507546 0.54569074]
 [0.45392496 0.98500587 0.19607708]
 [0.73321087 0.89439933 0.05936078]]
Matrix D:
 [[0.59782929 0.22254186 0.05658499]
 [0.34298087 0.75006597 0.12100103]
 [0.5476809  0.8996734  0.29385862]]


10

In [ ]:
matrix_4x4 = np.random.random((4, 4))
matrix_4x4_transpose = matrix_4x4.T
print("Matrix 4x4:, matrix_4x4")

Matrix 4x4:, matrix_4x4


11

In [4]:
matrix_3x3_det = np.random.random((3, 3))
determinant = np.linalg.det(matrix_3x3_det)
print("Matrix 3x3:", matrix_3x3_det)

Matrix 3x3: [[0.84106907 0.49423499 0.46840821]
 [0.24929058 0.45944639 0.52877696]
 [0.67513076 0.66025002 0.32405565]]


12

In [5]:
matrix_A_3x4 = np.random.random((3, 4))
matrix_B_4x3 = np.random.random((4, 3))
matrix_AB_product = np.dot(matrix_A_3x4, matrix_B_4x3)
print('Matrix A 3x4:', matrix_A_3x4)

Matrix A 3x4: [[0.66642174 0.85245473 0.59071728 0.5122132 ]
 [0.98259383 0.72018648 0.722941   0.59198691]
 [0.90159455 0.18463603 0.07835019 0.8590888 ]]


13

In [ ]:
matrix_3x3_rand = np.random.random((3, 3))
vector_3x1 = np.random.random((3, 1))
matrix_vector_product = np.dot(matrix_3x3_rand, vector_3x1)
print("Matrix 3x3 Random:", matrix_3x3_rand)
print("Vector 3x1:", vector_3x1)

Matrix 3x3 Random: [[0.31786429 0.80576537 0.62070326]
 [0.54646818 0.10020623 0.34623803]
 [0.93479823 0.15884754 0.02698974]]
Vector 3x1: [[0.2761462 ]
 [0.0506177 ]
 [0.98768178]]


14

In [ ]:
A_linear = np.random.random((3, 3))
b_linear = np.random.random((3, 1))
solution_x = np.linalg.solve(A_linear, b_linear)
print("Matrix A Linear:", A_linear)
print("Vector b Linear:", b_linear)

Matrix A Linear: [[0.54023311 0.76352083 0.20224952]
 [0.61617707 0.44016896 0.93719296]
 [0.93122883 0.9469256  0.92589326]]
Vector b Linear: [[0.93343119]
 [0.58556993]
 [0.79675944]]


15

In [ ]:
matrix_5x5 = np.random.random((5, 5))
row_sums = matrix_5x5.sum(axis=1)
column_sums = matrix_5x5.sum(axis=0)
print("Matrix 5x5:", matrix_5x5)
print("Row Sums: ", row_sums)

Matrix 5x5: [[0.77205942 0.78959606 0.28726741 0.7458041  0.57460654]
 [0.60638569 0.75762285 0.44042407 0.2091505  0.64211669]
 [0.71193944 0.72094302 0.6566151  0.06296158 0.97664931]
 [0.49662414 0.82266067 0.34586581 0.33538614 0.29622647]
 [0.01450132 0.50297346 0.36492539 0.49680431 0.20790039]]
Row Sums:  [3.16933353 2.65569981 3.12910844 2.29676323 1.58710487]
