1

In [4]:
import numpy as np

vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2

In [5]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3

In [6]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4

In [7]:
array_3x3x3 = np.random.random((3, 3, 3))
print("3x3x3 Random Array:\n", array_3x3x3)


3x3x3 Random Array:
 [[[0.68810864 0.1102364  0.9413054 ]
  [0.94396798 0.7548933  0.6248229 ]
  [0.74367798 0.96024438 0.25729066]]

 [[0.04269686 0.85558112 0.66305986]
  [0.27613061 0.86307701 0.37695258]
  [0.30651146 0.72086073 0.21882711]]

 [[0.47393477 0.9691099  0.59357695]
  [0.13087958 0.65693145 0.66854897]
  [0.4160085  0.07051467 0.2686296 ]]]


5

In [8]:
array_10x10 = np.random.random((10, 10))
min_value = array_10x10.min()
max_value = array_10x10.max()
print("\n10x10 Random Array:\n", array_10x10)
print("Min Value:", min_value, "Max Value:", max_value)


10x10 Random Array:
 [[0.07958495 0.50592427 0.15504809 0.83153646 0.71253536 0.94034614
  0.31701106 0.84365229 0.46100869 0.60873355]
 [0.78637514 0.53998923 0.74480184 0.41942901 0.79609317 0.7495621
  0.55999044 0.15463933 0.34926094 0.77029348]
 [0.97557846 0.07476388 0.2765849  0.55302352 0.75816934 0.77619054
  0.89855673 0.80450738 0.7654856  0.30319771]
 [0.122447   0.39374485 0.36892322 0.69228747 0.38329233 0.651156
  0.02698211 0.75670979 0.11752761 0.99587968]
 [0.161483   0.68850851 0.76126478 0.52121288 0.97291527 0.02215898
  0.65080377 0.80298049 0.23487535 0.76280204]
 [0.21553631 0.49947422 0.22282621 0.37760688 0.57087817 0.64926179
  0.68409832 0.70163679 0.48352403 0.72900631]
 [0.87133047 0.71919802 0.18834272 0.0440871  0.8454157  0.84291445
  0.92907558 0.36743606 0.92445965 0.84517183]
 [0.82037671 0.01924274 0.30787706 0.65337715 0.56067871 0.48521105
  0.69295603 0.84467518 0.76927356 0.767011  ]
 [0.81668702 0.84051685 0.57769252 0.93907238 0.56718468 0.13

6

In [9]:
vector_30 = np.random.random(30)
mean_value = vector_30.mean()
print("\nMean Value of Random Vector:", mean_value)


Mean Value of Random Vector: 0.5599611682592738


7

In [10]:
matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (matrix_5x5 - np.min(matrix_5x5)) / (np.max(matrix_5x5) - np.min(matrix_5x5))
print("\nNormalized 5x5 Matrix:\n", normalized_matrix)



Normalized 5x5 Matrix:
 [[0.44511799 0.99445586 0.02424992 1.         0.05391142]
 [0.80965261 0.36179645 0.24591822 0.46595867 0.55193511]
 [0.0181371  0.86439975 0.80057203 0.17349997 0.41507988]
 [0.50098403 0.         0.63288942 0.72206457 0.85812288]
 [0.77281625 0.27444182 0.81491344 0.7508063  0.79542663]]


8

In [11]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
matrix_product = np.dot(matrix_5x3, matrix_3x2)
print("\nMatrix Product (5x3) * (3x2):\n", matrix_product)


Matrix Product (5x3) * (3x2):
 [[1.17820881 0.87458822]
 [1.40661403 1.15207951]
 [0.47716632 0.43238317]
 [1.26972155 0.96423541]
 [0.50398034 0.41185655]]


9

In [12]:
matrix_A = np.random.random((3, 3))
matrix_B = np.random.random((3, 3))
dot_product = np.dot(matrix_A, matrix_B)
print("\nDot Product of Two 3x3 Matrices:\n", dot_product)


Dot Product of Two 3x3 Matrices:
 [[0.65344402 1.05253287 0.58397049]
 [0.63746025 1.01201629 0.73730325]
 [0.51557855 0.83161272 1.0433787 ]]


10

In [13]:
matrix_4x4 = np.random.random((4, 4))
transpose_matrix = matrix_4x4.T
print("\nTranspose of 4x4 Matrix:\n", transpose_matrix)


Transpose of 4x4 Matrix:
 [[0.99587238 0.39009456 0.80275822 0.43015987]
 [0.95379891 0.621983   0.39904665 0.83047387]
 [0.3458431  0.4027437  0.88442408 0.49386617]
 [0.57112402 0.34090737 0.48699641 0.38531484]]


11

In [14]:
matrix_3x3 = np.random.random((3, 3))
determinant = np.linalg.det(matrix_3x3)
print("\nDeterminant of 3x3 Matrix:", determinant)


Determinant of 3x3 Matrix: 0.4754468006608953


12

In [15]:
matrix_A_3x4 = np.random.random((3, 4))
matrix_B_4x3 = np.random.random((4, 3))
matrix_product_AB = np.dot(matrix_A_3x4, matrix_B_4x3)
print("\nMatrix Product (3x4) * (4x3):\n", matrix_product_AB)


Matrix Product (3x4) * (4x3):
 [[1.07889718 0.45328035 0.50417449]
 [0.33152154 0.28403484 0.12723134]
 [1.47837842 0.50555575 0.69989013]]


13

In [16]:
matrix_3x3 = np.random.random((3, 3))
vector_3x1 = np.random.random((3, 1))
matrix_vector_product = np.dot(matrix_3x3, vector_3x1)
print("\nMatrix-Vector Product:\n", matrix_vector_product)


Matrix-Vector Product:
 [[0.43747271]
 [0.25488665]
 [0.58643248]]


14

In [17]:
A = np.random.random((3, 3))
b = np.random.random((3, 1))
x = np.linalg.solve(A, b)
print("\nSolution to Ax = b:\n", x)



Solution to Ax = b:
 [[ 0.22929221]
 [ 0.27769062]
 [-0.30897254]]


15

In [18]:
matrix_5x5 = np.random.random((5, 5))
row_sums = matrix_5x5.sum(axis=1)  
column_sums = matrix_5x5.sum(axis=0)
print("\nRow-wise Sums:\n", row_sums)
print("Column-wise Sums:\n", column_sums)


Row-wise Sums:
 [2.85132821 2.74239227 2.90053614 3.14618265 1.54636198]
Column-wise Sums:
 [2.79063124 2.11188572 2.75015711 2.90490966 2.62921751]
