In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
def fahrenheit_to_celsius(F):
    return (F - 32) * 5 / 9
vectorized_conversion = np.vectorize(fahrenheit_to_celsius)
temps_f = np.array([32, 68, 100, 212, 77])
temps_c = vectorized_conversion(temps_f)

print("Temperatures in Fahrenheit:", temps_f)
print("Temperatures in Celsius:", temps_c)


Temperatures in Fahrenheit: [ 32  68 100 212  77]
Temperatures in Celsius: [  0.          20.          37.77777778 100.          25.        ]


In [5]:
def power_function(base,exp):
    return base**exp
vectoized_power = np.vectorize(power_function)
base= np.array([2, 3, 4, 5, 6])
exp= np.array([1,2,3,4,5])   
print("asoslar", base)

asoslar [2 3 4 5 6]


In [6]:
w=np.array([
          [4,5,6],
          [3,-1,1],
          [2,1,-2]
])
y=np.array([7,4,5])
np.linalg.solve(w,y)

array([ 1.7027027 ,  0.62162162, -0.48648649])

In [7]:
w=np.array([
          [10,-2,3],
          [-2,8,-3],
          [3,-2,3]
])
y=np.array([12,-5,15])
np.linalg.solve(w,y)

array([-0.42857143,  1.73809524,  6.58730159])

**IMAGE**

In [8]:
pip install pillow

Note: you may need to restart the kernel to use updated packages.


In [9]:
from PIL import Image

In [10]:
with Image.open('images/bird.jpg') as img:
    img_arr=np.array(img)

In [11]:
img_arr.shape

(1080, 1920, 3)

In [12]:
pip install pillow

Note: you may need to restart the kernel to use updated packages.


In [13]:
from PIL import Image
import numpy as np
image = Image.open('images/bird.jpg')
image_array = np.array(image)
rotated_image_array = np.rot90(image_array, k=1)
rotated_image = Image.fromarray(rotated_image_array)
rotated_image.save('images/rotated_image.jpg')

In [14]:
with Image.open('images/bird.jpg') as img:
    print(img.mode)
    img_arr=np.array(img)

RGB


In [15]:
img_arr.shape

(1080, 1920, 3)

In [16]:
img_arr[0,0]

array([ 0, 31,  2], dtype=uint8)

In [17]:
img_arr

array([[[ 0, 31,  2],
        [ 0, 32,  3],
        [ 0, 33,  4],
        ...,
        [ 0, 12,  2],
        [ 0, 12,  2],
        [ 0, 12,  2]],

       [[ 0, 33,  4],
        [ 0, 33,  4],
        [ 1, 34,  5],
        ...,
        [ 1, 13,  3],
        [ 1, 13,  3],
        [ 1, 13,  3]],

       [[ 0, 33,  4],
        [ 0, 33,  4],
        [ 1, 34,  5],
        ...,
        [ 2, 14,  4],
        [ 2, 14,  4],
        [ 2, 14,  4]],

       ...,

       [[13, 18, 11],
        [13, 18, 11],
        [13, 18, 11],
        ...,
        [ 0, 16,  7],
        [ 5, 24, 18],
        [31, 50, 44]],

       [[14, 19, 12],
        [14, 19, 12],
        [13, 18, 11],
        ...,
        [ 0, 14,  6],
        [ 0,  9,  1],
        [ 0, 12,  4]],

       [[16, 21, 14],
        [15, 20, 13],
        [13, 18, 11],
        ...,
        [ 6, 23, 15],
        [ 5, 20, 13],
        [ 0, 12,  5]]], shape=(1080, 1920, 3), dtype=uint8)

In [18]:
gray_img_arr=img_arr[:,:,0]*0.299+img_arr[:,:,1]*0.587+img_arr[:,:,2]*0.114

In [19]:
gray_img_arr


array([[18.425, 19.126, 19.827, ...,  7.272,  7.272,  7.272],
       [19.827, 19.827, 20.827, ...,  8.272,  8.272,  8.272],
       [19.827, 19.827, 20.827, ...,  9.272,  9.272,  9.272],
       ...,
       [15.707, 15.707, 15.707, ..., 10.19 , 17.635, 43.635],
       [16.707, 16.707, 15.707, ...,  8.902,  5.397,  7.5  ],
       [18.707, 17.707, 15.707, ..., 17.005, 14.717,  7.614]],
      shape=(1080, 1920))

In [20]:
gray_img_arr.shape

(1080, 1920)

In [21]:
with Image.open('images/bird.jpg') as img:
    img_g=img.convert(mode='L')          
    img_g.save('gray_img.jpg')     

task3

In [39]:
%pip install opencv-python
import cv2
import numpy as np

def brighten_channel(image_path, channel_index, brightness_increase, output_path):
    image = cv2.imread(image_path)
    if image is None:
        raise ValueError("Image not found or unable to read.")
    
    # Split the image into B, G, R channels
    channels = cv2.split(image)
    
    # Increase brightness in the specified channel
    channels[channel_index] = np.clip(channels[channel_index] + brightness_increase, 0, 255)
    
    # Merge the channels back
    brightened_image = cv2.merge(channels)
    
    # Save the modified image
    cv2.imwrite(output_path, brightened_image)
    print(f"Modified image saved as {output_path}")

# Example usage
brighten_channel('bird.jpg', 2, 40, 'masked_output.jpg')  # Increases red channel brightness by 40


   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/29.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/29.4 MB ? eta -:--:--
   -----------------

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 810549cb2a4aedaa84ad9a1c92fbfdfc14090e2749cedf2c1589ad8359aa169b
             Got        4826243000cafbd4a7ec4e1e7242ed5f66abe2cd847154dcecb45e74c733c234



ModuleNotFoundError: No module named 'cv2'